[package]
authors = ["Navitia <navitia@kisio.org>"]
description = "Building GTFS transfers.txt file from GTFS stops.txt."
name = "transfe_rs"
version = "0.1.0"

[dependencies]
csv = "1.0.0-beta.3"
serde = "1.0.10"
serde_derive = "1.0.10"
structopt = "0.0.5"
structopt-derive = "0.0.5"
